export const cardData = [
  { id: 1, status: "", image: "/images/1.jpg" },
  { id: 1, status: "", image: "/images/1.jpg" },
  { id: 2, status: "", image: "/images/2.jpg" },
  { id: 2, status: "", image: "/images/2.jpg" },
  { id: 3, status: "", image: "/images/3.jpg" },
  { id: 3, status: "", image: "/images/3.jpg" },
  { id: 4, status: "", image: "/images/4.jpg" },
  { id: 4, status: "", image: "/images/4.jpg" },
  //   { id: 5, status: "", image: "/images/5.jpg" },
  //   { id: 5, status: "", image: "/images/5.jpg" },
  //   { id: 6, status: "", image: "/images/6.jpg" },
  //   { id: 6, status: "", image: "/images/6.jpg" },
  //   { id: 7, status: "", image: "/images/7.jpg" },
  //   { id: 7, status: "", image: "/images/7.jpg" },
  //   { id: 8, status: "", image: "/images/8.jpg" },
  //   { id: 8, status: "", image: "/images/8.jpg" },
];
